services:
  web:
    image: django_app
    container_name: django_app
    build:
      context: ./mysite
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/app