# Generated by Django 5.1.1 on 2024-09-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
