# Generated by Django 5.1.1 on 2024-09-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_update_at_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
