services:
  web:
    image: django_app
    container_name: book
    build:
      context: ./biblioteca
    ports:
      - "8000:8000"
    volumes:
      - ./biblioteca:/app
    depends_on:
      - mysql
 
  mysql:
     image: mysql:latest
     ports:
       - "3307:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=default
     volumes:
       - mysql_data:/data/db
       - ./mysql-init:/docker-entrypoint-initdb.d:ro
volumes:
  mysql_data: